<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tamara Vilches">

<title>Nivel educativo y desafección: estudio sobre el interés político en Chile.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="plantilla_informe_files/libs/clipboard/clipboard.min.js"></script>
<script src="plantilla_informe_files/libs/quarto-html/quarto.js"></script>
<script src="plantilla_informe_files/libs/quarto-html/popper.min.js"></script>
<script src="plantilla_informe_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="plantilla_informe_files/libs/quarto-html/anchor.min.js"></script>
<link href="plantilla_informe_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="plantilla_informe_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="plantilla_informe_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="plantilla_informe_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="plantilla_informe_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="plantilla_informe_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="plantilla_informe_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Nivel educativo y desafección: estudio sobre el interés político en Chile.</h1>
<p class="subtitle lead">R para el Análisis de datos sociales 2026</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Tamara Vilches </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">21 de abril de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introducción." class="level2">
<h2 class="anchored" data-anchor-id="introducción.">Introducción.</h2>
<p>El siguiente trabajo trabaja el tema de cómo la influencia de la trayectoria educativa afecta en la configuración del interés político, la percepción de las instituciones y la participación electoral en Chile. Para este trabajo se utiliza la base de datos de ELSOC.</p>
</section>
<section id="planteamiento-del-problema." class="level2">
<h2 class="anchored" data-anchor-id="planteamiento-del-problema.">Planteamiento del problema.</h2>
<p>En las últimas décadas, la democracia chilena ha transitado por un escenario de transformaciones estructurales que han puesto en evidencia una profunda desconexión entre la ciudadanía y sus instituciones. Este fenómeno, el cual es definido como una <em>encrucijada conceptual</em> <span class="citation" data-cites="mardonesa.2014">(<a href="#ref-mardonesa.2014" role="doc-biblioref">Mardones A. 2014</a>)</span>, sugiere que la desafección política no es un evento azaroso, sino que es un proceso arraigado en la estructura social. En este contexto, el <strong>nivel educativo</strong> emerge como una variable crítica para entender por qué ciertos sectores de la población mantienen un interés activo en la esfera pública, mientras que otros se repliegan hacia la apatía.</p>
<p>El problema central radica en que la desigualdad educativa en Chile se traduce en una desigualdad de capacidades políticas. Si el sistema educativo no logra dotar a los ciudadanos de las herramientas necesarias para procesar la complejidad del sistema, la democracia corre el riesgo de volverse excluyente. Por lo tanto, este trabajo busca examinar cómo la experiencia educativa moldea el <strong>interés político</strong>, actuando como el principal predictor de la integración o alineación del ciudadano/a respecto al poder político nacional.</p>
</section>
<section id="teoría-de-la-socialización-y-educación-secundaria." class="level2">
<h2 class="anchored" data-anchor-id="teoría-de-la-socialización-y-educación-secundaria.">Teoría de la socialización y educación secundaria.</h2>
<p>La construcción del interés político no es un proceso que comience con la mayoría de edad, sino que se gesta durante la etapa escolar mediante la socialización política primaria, la relación entre el nivel educativo y la vida pública no es directa, sino que se construye a través de la <strong>eficacia política interna</strong>. Sobre esto, [<span class="citation" data-cites="muñoz-labraña2016">Muñoz-Labraña, Martínez-Rodríguez, y Muñoz-Grandón (<a href="#ref-muñoz-labraña2016" role="doc-biblioref">2016</a>)</span> demuestran que, al finalizar la educación secundaria en Chile, el estudiantado ya posee percepciones profundamente críticas y a menudo negativas sobre los partidos y los actores políticos; por lo que el sistema escolar es el primer espacio donde el estudiante evalúa sus propias competencias para entender el entorno político. El nivel educativo no solo entrega datos, sino que dota al individuo de herramientas analíticas que elevan su interés. Como bien señala <span class="citation" data-cites="mardonesa.2014">(<a href="#ref-mardonesa.2014" role="doc-biblioref">Mardones A. 2014</a>)</span>, cuando la educación falla en este proceso de socialización, la baja eficacia política percibida se traduce en desafección, transformando el desinterés inicial en un alejamiento permanente de las instituciones.</p>
</section>
<section id="hipótesis." class="level2">
<h2 class="anchored" data-anchor-id="hipótesis.">Hipótesis.</h2>
<p>El nivel educativo alcanzado por las y los ciudadanos chilenos actúa como un determinante del interés político, el cual es mediado por el desarrollo de la eficacia política. Se postula que una mayor trayectoria académica fortalece las capacidades cognitivas para comprender el sistema, aumentando la eficacia política interna; este sentimiento de competencia es el que finalmente impulsa una mayor participación electoral y reduce la desafección institucional <span class="citation" data-cites="mackenna2015">(<a href="#ref-mackenna2015" role="doc-biblioref">Mackenna 2015</a>)</span>.</p>
</section>
<section id="variables." class="level2">
<h2 class="anchored" data-anchor-id="variables.">Variables.</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data"</code></pre>
</div>
</div>
<p>Para continuar la investigación, pasaré a describir el conjunto de variables a utilizar.</p>
<section id="descripción-de-variables." class="level3">
<h3 class="anchored" data-anchor-id="descripción-de-variables.">Descripción de variables.</h3>
<p>Para este trabajo, se seleccionaron las variables:</p>
<ul>
<li>Nivel educacional (m01): variable de tipo <strong>ordinal</strong> que mide el nivel educacional alcanzado por el encuestado. La pregunta utilizada en la encuesta es: <em>¿Cuál es tu nivel educacional?</em>. Las categorías reflejan una progresión jerárquica de menor a mayor nivel de estudios, lo que permite ordenar a los individuos según su trayectoria académica. Esta es la <strong>variable independiente principal</strong> de este estudio, ya que da cuenta del capital educativo de los individuos.</li>
<li>Interés en la política (c13): variable de tipo <strong>ordinal</strong> que mide el grado de interés del encuestado en la política. La pregunta utilizada es: <em>¿Qué tan interesado está usted en la política?</em>. Sus categorías reflejan distintos niveles de interés, desde bajo a alto. Esta variable representa una dimensión subjetiva del involucramiento político, vinculada a la disposición de los individuos a informarse y participar en asuntos públicos.</li>
<li>Frecuencia de información política (c14_02): variable de tipo <strong>ordinal</strong> que mide la frecuencia con la cual el encuestado se informa sobre política a través de distintos medios. Su pregunta es: <em>¿Con qué frecuencia se informa sobre política?</em>. Esta variable representa una dimensión conductual del involucramiento político, en tanto da cuenta de prácticas concretas de consumo de información política.</li>
<li>Participación electoral (c11): variable <strong>nominal</strong> que mide si el encuestado participó en la última elección. A partir de esta podemos distinguir entre quienes votaron y quienes no. Esta variable representa una medida concreta de comportamiento político, a diferencia de otras variables que capturan actitudes o percepciones. Esta es la <strong>variable dependiente principal</strong> de este estudio.</li>
<li>Participación política no electoral (c07_02): variable de tipo <strong>ordinal</strong> que mide la participación del encuestado en actividades políticas distintas del voto, como la asistencia a reuniones o instancias de discusión pública. La pregunta utilizada es: <em>¿Ha participado en reuniones sobre temas de interés público?</em>. Esta variable representa una dimensión ampliada de la participación política, que va más allá del acto electoral.</li>
<li>Edad (m0_edad): variable de tipo <strong>de razón</strong> que mide la edad del encuestado en años cumplidos. La variable representa una característica sociodemográfica estructural que influye en el comportamiento político, dado que distintos grupos etarios presentan patrones diferenciados de participación e interés en la política.</li>
<li>Confianza en partidos políticos (c05_02): variable de tipo <strong>ordinal</strong> (variable de intervalo) que mide el nivel de confianza del encuestado en los partidos políticos. Representa una dimensión de la relación entre los ciudadanos y las instituciones políticas, particularmente en término de legitimidad y confianza. Su relevancia para este estudio es que permite agregar la dimensión de de desafección institucional, la cual es relevante para la hipótesis planteada.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="https://chilepsicologos.cl/wp-content/uploads/2024/04/educacion1234-1.jpg" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="análisis." class="level2">
<h2 class="anchored" data-anchor-id="análisis.">Análisis.</h2>
<p>Los resultados presentes en <a href="#tbl-voto" class="quarto-xref">Tabla&nbsp;1</a> muestran la distribución de la participación electoral en la muestra analizada. Se observa la proporción de individuos que declararon haber votado en la última elección en comparación con aquellos que no participaron. Esta variable permite identificar el nivel general de involucramiento electoral en la población estudiada.</p>
<p>En términos analíticos, esta distribución constituye un punto de partida para evaluar la hipótesis de investigación, ya que permite observar el comportamiento político efectivo de los individuos. En este sentido, la participación electoral se configura como una variable clave para analizar si factores como el nivel educacional y el interés político inciden en la probabilidad de votar.</p>
<div class="cell" data-tbl-cap-location="top">
<div id="tbl-voto" class="cell quarto-float anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-voto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;1: Distribución de la participación electoral
</figcaption>
<div aria-describedby="tbl-voto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Votó en última elección</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Proporción (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Sí votó</td>
<td style="text-align: center;">1939</td>
<td style="text-align: center;">68.08</td>
</tr>
<tr class="even">
<td style="text-align: center;">No votó</td>
<td style="text-align: center;">909</td>
<td style="text-align: center;">31.92</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: center; padding: 0; border: 0;"><sup>a</sup> Fuente: Elaboración propia en base a ELSOC 2016-2022</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</figure>
</div>
</div>
<p>La distribución del nivel educacional presente en <a href="#tbl-educacion" class="quarto-xref">Tabla&nbsp;2</a> muestra la composición de la muestra en términos de trayectoria académica. Se identifican distintas categorías que reflejan niveles crecientes de educación formal.</p>
<p>Esta variable resulta central para el análisis, ya que permite evaluar diferencias en el comportamiento político según el capital educativo de los individuos. Desde la perspectiva teórica adoptada, se espera que mayores niveles educacionales se asocien con un mayor interés en la política y, consecuentemente, con mayores niveles de participación electoral.</p>
<div class="cell">
<div id="tbl-educacion" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-educacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;2: Distribución del nivel educacional
</figcaption>
<div aria-describedby="tbl-educacion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Nivel educacional</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Proporción (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Básica</td>
<td style="text-align: center;">351</td>
<td style="text-align: center;">12.23</td>
</tr>
<tr class="even">
<td style="text-align: center;">Media</td>
<td style="text-align: center;">673</td>
<td style="text-align: center;">23.45</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Técnica</td>
<td style="text-align: center;">937</td>
<td style="text-align: center;">32.65</td>
</tr>
<tr class="even">
<td style="text-align: center;">Universitaria</td>
<td style="text-align: center;">909</td>
<td style="text-align: center;">31.67</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: center; padding: 0; border: 0;"><sup>a</sup> Fuente: Elaboración propia en base a ELSOC 2016-2022</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</figure>
</div>
</div>
<p>Los estadísticos descriptivos visualizados en <a href="#tbl-descriptivos" class="quarto-xref">Tabla&nbsp;3</a> permiten caracterizar la muestra en términos de edad y nivel de confianza en los partidos políticos. En particular, el promedio y la mediana de la edad entregan información sobre la distribución etaria de los encuestados, mientras que la desviación estándar permite observar la dispersión de estos valores.</p>
<p>Por su parte, los indicadores de confianza en los partidos políticos permiten aproximarse a la relación entre los ciudadanos y las instituciones políticas. Esta dimensión es relevante para el análisis, ya que niveles más altos de desconfianza podrían asociarse a menores niveles de participación política.</p>
<div class="cell" data-tbl-cap-location="top">
<div id="tbl-descriptivos" class="cell quarto-float anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-descriptivos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;3: Estadísticos descriptivos de edad y confianza en partidos políticos
</figcaption>
<div aria-describedby="tbl-descriptivos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="lightable-classic do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Edad promedio</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Edad mediana</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Edad SD</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Confianza promedio</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Confianza mediana</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Confianza SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">46.00244</td>
<td style="text-align: center;">46</td>
<td style="text-align: center;">15.24741</td>
<td style="text-align: center;">1.386411</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.6814962</td>
</tr>
</tbody><tfoot>
<tr class="even">
<td style="text-align: center; padding: 0; border: 0;"><sup>a</sup> Fuente: Elaboración propia en base a ELSOC 2016-2022</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="plantilla_informe_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="relación-entre-nivel-educacional-y-participación-electoral" class="level3">
<h3 class="anchored" data-anchor-id="relación-entre-nivel-educacional-y-participación-electoral">Relación entre nivel educacional y participación electoral</h3>
<p>En <a href="#fig-educacion-voto" class="quarto-xref">Figura&nbsp;1</a> muestra una asociación entre el nivel educacional y la participación electoral, medida como la proporción de individuos que declaran haber votado. Se observa una tendencia positiva: a medida que aumenta el nivel educacional, también lo hace la proporción de personas que participan en elecciones.</p>
<p>Esta relación sugiere que la educación podría estar vinculada al desarrollo de recursos cognitivos y cívicos que facilitan la comprensión del sistema político y la toma de decisiones electorales. Asimismo, los niveles más altos de educación tienden a concentrarse en individuos con mayor edad promedio, lo que también podría influir en mayores niveles de participación, dado que la edad ha sido identificada como un factor relevante en el comportamiento electoral.</p>
<p>En términos de la hipótesis planteada, estos resultados son consistentes con la idea de que una mayor trayectoria educativa contribuye indirectamente a una mayor participación política, posiblemente mediada por variables como la eficacia política.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-educacion-voto" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-educacion-voto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="plantilla_informe_files/figure-html/fig-educacion-voto-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-educacion-voto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Relación entre nivel educacional y participación electoral
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="plantilla_informe_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="relación-entre-nivel-educacional-e-interés-político." class="level3">
<h3 class="anchored" data-anchor-id="relación-entre-nivel-educacional-e-interés-político.">Relación entre nivel educacional e interés político.</h3>
<p>El <a href="#fig-educacion-interes" class="quarto-xref">Figura&nbsp;2</a> evidencia una relación positiva entre el nivel educacional y el interés político promedio. Los grupos con mayor nivel educativo presentan, en promedio, mayores niveles de interés en la política, lo que sugiere que la educación no solo influye en comportamientos observables como el voto, sino también en dimensiones actitudinales.</p>
<p>Este patrón puede interpretarse como resultado del fortalecimiento de habilidades cognitivas asociadas a la educación, las cuales permiten una mejor comprensión de los procesos políticos, aumentando así el involucramiento subjetivo con estos temas. Además, el interés político es un componente clave de la eficacia política interna, entendida como la percepción de competencia para participar en política.</p>
<p>En relación con la hipótesis, este hallazgo es especialmente relevante, ya que respalda el mecanismo teórico propuesto: la educación incrementa el interés político, lo que a su vez podría fortalecer la eficacia política y, finalmente, traducirse en mayores niveles de participación electoral.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-educacion-interes" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-educacion-interes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="plantilla_informe_files/figure-html/fig-educacion-interes-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-educacion-interes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Relación entre nivel educacional e interés político
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="conclusión." class="level2">
<h2 class="anchored" data-anchor-id="conclusión.">Conclusión.</h2>
<p>Para concluir, podemos decir que ambos gráficos sugieren que el nivel educacional no solo se asocia con comportamientos políticos concretos, como la participación electoral. Sino también se asocia con disposiciones subjetivas como el interés político, lo que refuerza su rol como un determinante central en la configuración de la relación entre ciudadanía y política.</p>
</section>
<section id="tabla-de-correlaciones." class="level2">
<h2 class="anchored" data-anchor-id="tabla-de-correlaciones.">Tabla de correlaciones.</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">&nbsp;</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">voto_bin</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">confianza_partidos</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">participacion</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">info_politica</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">interes_politico</td>
<td data-quarto-table-cell-role="th" style="font-style: italic; font-weight: normal; border-top: double black; border-bottom: 1px solid black; padding: 0.2cm">edad</td>
</tr>
<tr class="even">
<td style="font-style: italic">voto_bin</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">confianza_partidos</td>
<td style="text-align: center; padding: 0.2cm;">0.047<span style="vertical-align:super;font-size:0.8em;">*</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">participacion</td>
<td style="text-align: center; padding: 0.2cm;">0.126<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.072<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">info_politica</td>
<td style="text-align: center; padding: 0.2cm;">0.101<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.102<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.080<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td style="font-style: italic">interes_politico</td>
<td style="text-align: center; padding: 0.2cm;">0.155<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.278<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.144<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">0.408<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="odd">
<td style="font-style: italic">edad</td>
<td style="text-align: center; padding: 0.2cm;">0.351<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">-0.051<span style="vertical-align:super;font-size:0.8em;">**</span></td>
<td style="text-align: center; padding: 0.2cm;">0.098<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm; color: #999999;">-0.007<span style="vertical-align:super;font-size:0.8em;"></span></td>
<td style="text-align: center; padding: 0.2cm;">-0.098<span style="vertical-align:super;font-size:0.8em;">***</span></td>
<td style="text-align: center; padding: 0.2cm;">&nbsp;</td>
</tr>
<tr class="even">
<td colspan="7" style="text-align: right; border-bottom: double black; border-top: 1px solid black; font-style: italic; font-size: 0.9em;">Computed correlation used pearson-method with listwise-deletion.</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>En general, las correlaciones observadas son <em>bajas a moderadas</em>, lo que indica asociaciones existentes, pero no muy fuertes entre las variables analizadas.</p>
<p>En primer lugar, la variable voto_bin presenta correlaciones positivas con la mayoría de las variables, destacando su relación con la edad <strong>(r = 0.351)</strong>, que corresponde a una correlación moderada, lo que sugiere que las personas de mayor edad tienden a votar más. Asímismo, se observan correlaciones bajas pero de todas formas significativas, con las variables interés político <strong>(r = 0.155)</strong>, participación <strong>(r = 0.126)</strong> e información política <strong>(r = 0.101)</strong>.</p>
<p>Por su parte, el interés político muestra una correlación moderada con la información política <strong>(r = 0.408)</strong>, indicando que quienes están más informados tienden también a mostrar mayor interés político. Además, presenta una correlación moderada con la confianza en partidos <strong>(r = 0.278)</strong> y baja con la participación <strong>(r = 0.144)</strong>.</p>
<p>En cuanto a la edad, se observa una correlación negativa baja con el interés político <strong>(r = -0.098)</strong> y prácticamente nula con la información política <strong>(r = -0.007)</strong>, lo que sugiere que la edad no está fuertemente asociada con estas dimensiones de nuestras variables.</p>
<p>Finalmente, la mayoría de las correlaciones son estadísticamente significativas (indicadas por asteríscos), aunque de <em>magnitud baja</em>, lo que de todas formas es común en estudios sociales.</p>
</section>
<section id="índice-escala-y-alfa-de-cronbach." class="level2">
<h2 class="anchored" data-anchor-id="índice-escala-y-alfa-de-cronbach.">Índice (escala) y Alfa de Cronbach.</h2>
<section id="alpha-de-cronbach." class="level3">
<h3 class="anchored" data-anchor-id="alpha-de-cronbach.">Alpha de Cronbach.</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = items)

  raw_alpha std.alpha G6(smc) average_r  S/N   ase mean   sd median_r
      0.48      0.47    0.43      0.18 0.88 0.014  1.9 0.64     0.12

    95% confidence boundaries 
         lower alpha upper
Feldt     0.44  0.48  0.51
Duhachek  0.45  0.48  0.50

 Reliability if an item is dropped:
                   raw_alpha std.alpha G6(smc) average_r  S/N alpha se  var.r
confianza_partidos      0.46      0.45    0.38     0.211 0.80    0.016 0.0305
participacion           0.51      0.52    0.45     0.263 1.07    0.014 0.0241
info_politica           0.37      0.37    0.30     0.166 0.59    0.019 0.0111
interes_politico        0.19      0.22    0.16     0.085 0.28    0.023 0.0002
                   med.r
confianza_partidos 0.143
participacion      0.280
info_politica      0.143
interes_politico   0.081

 Item statistics 
                      n raw.r std.r r.cor r.drop mean   sd
confianza_partidos 2870  0.46  0.58  0.33   0.21  1.4 0.68
participacion      2870  0.43  0.52  0.20   0.14  1.6 0.79
info_politica      2870  0.77  0.64  0.46   0.33  3.0 1.40
interes_politico   2870  0.76  0.74  0.65   0.47  1.7 1.07

Non missing response frequency for each item
                      1    2    3    4    5 miss
confianza_partidos 0.72 0.19 0.08 0.01 0.00    0
participacion      0.59 0.22 0.19 0.00 0.00    0
info_politica      0.22 0.12 0.29 0.18 0.20    0
interes_politico   0.61 0.18 0.12 0.06 0.03    0</code></pre>
</div>
</div>
</section>
<section id="creación-y-gráfico-del-índice." class="level3">
<h3 class="anchored" data-anchor-id="creación-y-gráfico-del-índice.">Creación y gráfico del índice.</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="plantilla_informe_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="breve-interpretación." class="level2">
<h2 class="anchored" data-anchor-id="breve-interpretación.">Breve interpretación.</h2>
<p>El gráfico anterior nos muestra la distribución del índice de interés político según el nivel educacional (básica, media, técnica y universitaria), utilizando para esto diagramas de caja. Podemos obsrvar una tendencia positiva entre nivel educativo e interés político; las personas con educación básica presentan los niveles más bajos del índice (mediana más baja), a medida que aumenta el nivel educativo (media y técnica) el índice también aumenta gradialmente, se observa también que el grupo con educación universitaria muestra los valores más altos del índice con una mediana claramente superior.</p>
<p>Si bien vemos que en todos los grupos hay cierta dispersión, los niveles más altos (sobretodo universitario) presentan mayor variabilidad, lo que indica diversidad en el interés político dentro del grupo. Se logran observar algunos valores atípicos en todos los niveles, lo que sugiere que hay casos individuales con niveles de interés político inusualmente altos.</p>
<p>Finalmente podemos interpretar que el nivel educativo se aosica positivamente con el interés político, indicando que a mayor educación, existe mayor involucramiento y atención hacia los asuntos políticos. Los resultados expuestos evidencian que los niveles educatuvos más bajos concentran mayores niveles de desafección política, mientras que quienes poseen educación superior muestran mayor interés e involucramiento político.</p>
<p>En conjunto, el gráfico logra respaldar la hipótesis de que el nivel educativo constituye un factor relevante en la configuración del interés político, mostrando una relación positiva entre ambas variables.</p>
</section>
<section id="modelos-de-regresión." class="level2">
<h2 class="anchored" data-anchor-id="modelos-de-regresión.">Modelos de regresión.</h2>
<section id="tabla-de-regresiones." class="level3">
<h3 class="anchored" data-anchor-id="tabla-de-regresiones.">Tabla de regresiones.</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Modelo 1</td>
<td colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Modelo 2</td>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">std. Error</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">std. Error</td>
<td style="text-align: center;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.65</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.03</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.88</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.06</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">educacion cat [Media]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.16</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.04</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.17</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.04</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">educacion cat [Técnica]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.24</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.04</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.29</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.04</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">educacion cat<br>
[Universitaria]</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.53</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.04</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.52</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.04</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">edad</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.00</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">confianza partidos</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.42</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.01</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">2870</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">2870</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.079 / 0.079</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.278 / 0.277</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Los resultados de los modelos de regresión muestran que el nivel educativo tiene un efecto positivo y estadísticamente significativo sobre el interés político. En el Modelo 1, en comparación con la categoría de referencia (educación básica), quienes poseen educación media presentan un aumento de 0.16 unidades en el índice de interés político (p &lt; 0.001), quienes tienen educación técnica aumentan en 0.24 unidades (p &lt; 0.001), y quienes alcanzan educación universitaria muestran un incremento de 0.53 unidades (p &lt; 0.001). Estos resultados evidencian un claro gradiente educacional en el interés político.</p>
<p>Al incorporar variables de control en el Modelo 2, los efectos de la educación se mantienen e incluso aumentan levemente: educación media (0.17, p &lt; 0.001), educación técnica (0.29, p &lt; 0.001) y educación universitaria (0.52, p &lt; 0.001). Esto sugiere que la relación entre educación e interés político es robusta y no se explica por la inclusión de otras variables.</p>
<p>Respecto a las variables de control, la edad presenta un coeficiente de 0.00 (p &lt; 0.001), lo que indica un efecto estadísticamente significativo pero sustantivamente muy pequeño sobre el interés político. En contraste, la confianza en los partidos políticos muestra un efecto considerablemente mayor, con un coeficiente de 0.42 (p &lt; 0.001), posicionándose como uno de los predictores más relevantes del modelo.</p>
<p>Finalmente, la capacidad explicativa del modelo mejora sustancialmente al incluir estas variables adicionales. Mientras el Modelo 1 presenta un R² de 0.079 (R² ajustado = 0.079), el Modelo 2 alcanza un R² de 0.278 (R² ajustado = 0.277), lo que indica un incremento importante en la varianza explicada del interés político.</p>
<p>En conjunto, estos resultados permiten concluir que el nivel educativo es un factor clave en la explicación del interés político, y que su efecto se mantiene incluso al considerar otras variables relevantes, destacando además el rol significativo de la confianza en los partidos políticos.</p>
</section>
<section id="gráfico-de-valores-predichos." class="level3">
<h3 class="anchored" data-anchor-id="gráfico-de-valores-predichos.">Gráfico de valores predichos.</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="plantilla_informe_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico de valores predichos muestra una relación positiva y monotónica entre el nivel educativo y el índice de interés político. En particular, los valores estimados aumentan desde aproximadamente 1.63 en el nivel básico a 1.80 en educación media, 1.92 en educación técnica y 2.15 en educación universitaria.</p>
<p>Esta tendencia es consistente con los resultados del modelo de regresión, donde los coeficientes asociados a cada nivel educativo son positivos y estadísticamente significativos. Asimismo, los intervalos de confianza son relativamente estrechos y presentan escasa superposición, lo que refuerza la evidencia de diferencias sustantivas entre los grupos educativos.</p>
</section>
</section>
<section id="regresión-logística." class="level2">
<h2 class="anchored" data-anchor-id="regresión-logística.">Regresión logística.</h2>
<div class="cell">
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_6z8kmmouei6727kdg1zp = TinyTable.createTableFunctions("tinytable_6z8kmmouei6727kdg1zp");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '18', j: 2 } ], css_id: 'tinytable_css_3d7cagy1b5vczoqki47g',}, 
          { positions: [ { i: '12', j: 2 } ], css_id: 'tinytable_css_jrhk0amd84y4vppxed3h',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '16', j: 2 }, { i: '17', j: 2 } ], css_id: 'tinytable_css_2hrtxbsbnil3ahf43dk2',}, 
          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_5s0qrtfwv2fo98rdkynw',}, 
          { positions: [ { i: '18', j: 1 } ], css_id: 'tinytable_css_7jen5yt6bjqn9j9p58t1',}, 
          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_qsmhgv3a5vmhjwvdnl2r',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '16', j: 1 }, { i: '17', j: 1 } ], css_id: 'tinytable_css_8x93ob2lf543hyg3yxx2',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_hgdtfixjzmiofahw01zk',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_6z8kmmouei6727kdg1zp.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_6z8kmmouei6727kdg1zp td.tinytable_css_3d7cagy1b5vczoqki47g, #tinytable_6z8kmmouei6727kdg1zp th.tinytable_css_3d7cagy1b5vczoqki47g {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_6z8kmmouei6727kdg1zp td.tinytable_css_jrhk0amd84y4vppxed3h, #tinytable_6z8kmmouei6727kdg1zp th.tinytable_css_jrhk0amd84y4vppxed3h {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_6z8kmmouei6727kdg1zp td.tinytable_css_2hrtxbsbnil3ahf43dk2, #tinytable_6z8kmmouei6727kdg1zp th.tinytable_css_2hrtxbsbnil3ahf43dk2 { text-align: center }
    #tinytable_6z8kmmouei6727kdg1zp td.tinytable_css_5s0qrtfwv2fo98rdkynw, #tinytable_6z8kmmouei6727kdg1zp th.tinytable_css_5s0qrtfwv2fo98rdkynw {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_6z8kmmouei6727kdg1zp td.tinytable_css_7jen5yt6bjqn9j9p58t1, #tinytable_6z8kmmouei6727kdg1zp th.tinytable_css_7jen5yt6bjqn9j9p58t1 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_6z8kmmouei6727kdg1zp td.tinytable_css_qsmhgv3a5vmhjwvdnl2r, #tinytable_6z8kmmouei6727kdg1zp th.tinytable_css_qsmhgv3a5vmhjwvdnl2r {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_6z8kmmouei6727kdg1zp td.tinytable_css_8x93ob2lf543hyg3yxx2, #tinytable_6z8kmmouei6727kdg1zp th.tinytable_css_8x93ob2lf543hyg3yxx2 { text-align: left }
    #tinytable_6z8kmmouei6727kdg1zp td.tinytable_css_hgdtfixjzmiofahw01zk, #tinytable_6z8kmmouei6727kdg1zp th.tinytable_css_hgdtfixjzmiofahw01zk {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_6z8kmmouei6727kdg1zp" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">(1)</th>
              </tr>
        </thead>
        
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">(Intercept)</td>
                  <td data-row="1" data-col="2">-3.070</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.241)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">educacion_catMedia</td>
                  <td data-row="3" data-col="2">0.529</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.151)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">educacion_catTécnica</td>
                  <td data-row="5" data-col="2">0.906</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1"></td>
                  <td data-row="6" data-col="2">(0.149)</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">educacion_catUniversitaria</td>
                  <td data-row="7" data-col="2">1.513</td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1"></td>
                  <td data-row="8" data-col="2">(0.153)</td>
                </tr>
                <tr>
                  <td data-row="9" data-col="1">edad</td>
                  <td data-row="9" data-col="2">0.011</td>
                </tr>
                <tr>
                  <td data-row="10" data-col="1"></td>
                  <td data-row="10" data-col="2">(0.003)</td>
                </tr>
                <tr>
                  <td data-row="11" data-col="1">confianza_partidos</td>
                  <td data-row="11" data-col="2">1.242</td>
                </tr>
                <tr>
                  <td data-row="12" data-col="1"></td>
                  <td data-row="12" data-col="2">(0.077)</td>
                </tr>
                <tr>
                  <td data-row="13" data-col="1">Num.Obs.</td>
                  <td data-row="13" data-col="2">2870</td>
                </tr>
                <tr>
                  <td data-row="14" data-col="1">AIC</td>
                  <td data-row="14" data-col="2">3493.4</td>
                </tr>
                <tr>
                  <td data-row="15" data-col="1">BIC</td>
                  <td data-row="15" data-col="2">3529.2</td>
                </tr>
                <tr>
                  <td data-row="16" data-col="1">Log.Lik.</td>
                  <td data-row="16" data-col="2">-1740.717</td>
                </tr>
                <tr>
                  <td data-row="17" data-col="1">F</td>
                  <td data-row="17" data-col="2">73.522</td>
                </tr>
                <tr>
                  <td data-row="18" data-col="1">RMSE</td>
                  <td data-row="18" data-col="2">0.46</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">Referencias</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-mackenna2015" class="csl-entry" role="listitem">
Mackenna, Bernardo. 2015. <span>«Composición del electorado en elecciones con voto obligatorio y voluntario: un estudio cuasi experimental de la participación electoral en Chile»</span>. <em>Revista Lationamericana de Opinión Pública</em> vol 5 (junio). <a href="https://hdl.handle.net/10366/142679">https://hdl.handle.net/10366/142679</a>.
</div>
<div id="ref-mardonesa.2014" class="csl-entry" role="listitem">
Mardones A., Roberto. 2014. <span>«La encrucijada de la democracia chilena: una aproximación conceptual a la desafección política.»</span> <em>Pap.polit.</em> 19 (1): 3959. <a href="https://doi.org/10.11144/Javeriana.PAPO19-1.edca">https://doi.org/10.11144/Javeriana.PAPO19-1.edca</a>.
</div>
<div id="ref-muñoz-labraña2016" class="csl-entry" role="listitem">
Muñoz-Labraña, Carlos, Rosendo Martínez-Rodríguez, y Carlos Muñoz-Grandón. 2016. <span>«Perceptions of Students about Politics, Political Parties and Individuals Devoted to Politics when Ending High School Education in Chile»</span>. <em>Rev. Electr. Educare</em> 20 (1): 116. <a href="https://doi.org/10.15359/ree.20-1.17">https://doi.org/10.15359/ree.20-1.17</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>